# Generated by Django 5.2.6 on 2025-09-29 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener formato: +569XXXXXXXX o 9 dígitos', regex='^\\+?1?\\d{9,15}$')])),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
