# Generated by Django 5.2.6 on 2025-09-30 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_nombre_cliente_cliente_remove_cliente_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener formato: +569XXXXXXXX o 9 dígitos', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
