# Generated by Django 5.2.6 on 2025-09-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Rut',
            field=models.CharField(max_length=12),
        ),
    ]
