# Generated by Django 5.2.6 on 2025-10-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_empresa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
