# Generated by Django 5.2.6 on 2025-10-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cotizacion',
        ),
        migrations.DeleteModel(
            name='Cotizacion',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
