# Generated by Django 5.2.6 on 2025-10-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_empresa_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='item',
            name='servicio',
        ),
        migrations.AddField(
            model_name='item',
            name='cantidad_m3',
            field=models.DecimalField(decimal_places=2, default=23444, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='moneda',
            field=models.CharField(choices=[('CLP', 'Pesos Chilenos'), ('UF', 'UF')], default='CLP', max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
