# Generated by Django 5.2.6 on 2025-10-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_item_cantidad_remove_item_servicio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
