# Generated by Django 5.2.6 on 2025-10-02 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cliente',
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('valido_hasta', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='cotizacion',
            field=models.ForeignKey(default=324, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.cotizacion'),
            preserve_default=False,
        ),
    ]
