# Generated by Django 5.1.4 on 2025-10-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_item_cliente_cotizacion_item_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='moneda',
            field=models.CharField(choices=[('CLP', 'CLP'), ('UF', 'UF')], default='CLP', max_length=3),
        ),
    ]
