# Generated by Django 5.1.4 on 2025-10-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_item_moneda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='valido_hasta',
        ),
        migrations.AddField(
            model_name='item',
            name='valido_hasta',
            field=models.DateField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='descripcion',
            field=models.CharField(default=900, max_length=100),
            preserve_default=False,
        ),
    ]
