# Generated by Django 5.1.4 on 2025-10-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_cotizacion_valido_hasta_item_valido_hasta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='valido_hasta',
            field=models.DateField(),
        ),
    ]
