# Generated by Django 5.1.4 on 2025-10-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_cotizacion_numero_cotizacion_alter_item_valido_hasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='empresa',
            field=models.CharField(default=45, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.IntegerField(editable=False),
        ),
    ]
