# Generated by Django 5.2.6 on 2025-10-17 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_cotizacion_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cliente_temporal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
    ]
