# Generated by Django 5.2.6 on 2025-10-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_item_cliente_temporal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cliente_temporal',
        ),
    ]
