# Generated by Django 5.2.6 on 2025-10-17 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_item_cliente_temporal'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
    ]
