# Generated by Django 5.2.6 on 2025-10-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_item_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='valido_hasta',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='valido_hasta',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
