# Generated by Django 5.1.4 on 2025-10-17 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_item_valido_hasta_cotizacion_valido_hasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='valido_hasta',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
