# Generated by Django 5.1.4 on 2025-10-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_cotizacion_valido_hasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='valido_hasta',
            field=models.DateField(),
        ),
    ]
