# Generated by Django 5.1.4 on 2025-10-22 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_cotizacion_valido_hasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('vehiculo', models.CharField(max_length=100)),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('revision_tecnica', models.DateField()),
                ('circulacion', models.DateField()),
                ('seguro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='pdfs/')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.camiones')),
            ],
        ),
    ]
