# Generated by Django 5.1.4 on 2025-10-22 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_camiones_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='camion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app.camiones'),
        ),
    ]
