# Generated by Django 5.2.6 on 2025-10-24 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_empresas_trabajadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajadores',
            name='archivo',
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='app.empresas'),
        ),
        migrations.CreateModel(
            name='DocumentoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='pdfs/')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app.trabajadores')),
            ],
        ),
    ]
