# Generated by Django 5.1.4 on 2025-10-27 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_trabajadores_archivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosdePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('mes_servicio', models.CharField(max_length=20)),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Itemepp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_item', models.DateField()),
                ('material', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(max_length=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guia', models.IntegerField()),
                ('estados_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estadosdepago')),
            ],
        ),
    ]
