# Generated by Django 5.2.6 on 2025-10-27 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_estadosdepago_itemepp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadosdepago',
            name='precio_unitario',
        ),
    ]
