# Generated by Django 5.1.4 on 2025-10-28 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_estadosdepago_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemepp',
            name='estados_de_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.estadosdepago'),
        ),
    ]
