# Generated by Django 5.1.4 on 2025-10-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_itemepp_estados_de_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemepp',
            name='patente',
            field=models.CharField(default=-2007, max_length=20),
            preserve_default=False,
        ),
    ]
