# Generated by Django 5.1.4 on 2025-10-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_itemepp_patente'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadosdepago',
            name='usar_uf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estadosdepago',
            name='valor_uf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
