# Generated by Django 5.1.4 on 2025-11-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_estadosdepago_usar_uf_estadosdepago_valor_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condiciones',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
