# Generated by Django 5.1.4 on 2025-11-19 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_item_condiciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cotizacion')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estadosdepago')),
            ],
        ),
    ]
