# Generated by Django 5.1.4 on 2025-11-19 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_historial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='estado',
        ),
        migrations.AddField(
            model_name='historial',
            name='empresa',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historial',
            name='estado_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estadosdepago'),
        ),
        migrations.AddField(
            model_name='historial',
            name='pdf_url',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historial',
            name='tipo',
            field=models.CharField(choices=[('cotizacion', 'Cotización'), ('estado_pago', 'Estado de Pago')], default=-2014, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historial',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cotizacion'),
        ),
    ]
